ALTER TABLE "Character"
  ADD COLUMN "level"     INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "xp"        INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "inventory" JSONB   NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE "Character" ALTER COLUMN "x" SET DEFAULT 960;
ALTER TABLE "Character" ALTER COLUMN "y" SET DEFAULT 720;
